name: "Build: Tests validation"

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - '.github/**'
      - 'examples/**'
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - '.github/**'
      - 'examples/**'
  workflow_dispatch:

jobs:
  build:

    environment:
      name: "PyCheckpoint-API - Test environment on Ubuntu"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9, '3.10' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "dev_requirements.txt"
      - name: Configure the environment and additional libraries
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          pytest
