name: "Flake8 and Coverage"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'examples/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'examples/**'
  workflow_dispatch:

jobs:
  coverage:

    environment:
      name: "PyCheckpoint-API - Test environment on Ubuntu"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "dev_requirements.txt"
      - name: Configure the environment and additional libraries
        run: |
          pip install -e .
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest and coverage which generate a report
        run: |
          coverage run -m pytest
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
